const APP_ACTION = 'ruah/app';
export const LOAD_APP_ASSETS = `${APP_ACTION}/LOAD_APP_ASSETS`;
export const LOAD_APP_ASSETS_SUCCESS = `${APP_ACTION}/LOAD_APP_ASSETS_SUCCESS`;

const USER_ACTION = 'ruah/user';
export const APP_SUBMIT_LOGIN = `${USER_ACTION}/APP_SUBMIT_LOGIN`;
export const USER_SUBMIT_LOGIN = `${USER_ACTION}/USER_SUBMIT_LOGIN`;
export const SUBMIT_LOGIN_SUCCESS = `${USER_ACTION}/SUBMIT_LOGIN_SUCCESS`;
export const SUBMIT_LOGIN_FAIL = `${USER_ACTION}/SUBMIT_LOGIN_FAIL`;
export const SET_USER_ID = `${USER_ACTION}/SET_USER_ID`;
export const SET_PASSWORD = `${USER_ACTION}/SET_PASSWORD`;
