const APP_ACTION = 'ruah/app';
export const LAUNCH_APP = `${APP_ACTION}/LAUNCH_APP`;
export const LOAD_APP_ASSETS_SUCCESS = `${APP_ACTION}/LOAD_APP_ASSETS_SUCCESS`;
export const SET_SQL_STORE = `${APP_ACTION}/SET_SQL_STORE`;
export const SET_API_AUTH_TOKEN = `${APP_ACTION}/SET_API_AUTH_TOKEN`;

const USER_ACTION = 'ruah/user';
export const APP_SUBMIT_LOGIN = `${USER_ACTION}/APP_SUBMIT_LOGIN`;
export const USER_SUBMIT_LOGIN = `${USER_ACTION}/USER_SUBMIT_LOGIN`;
export const SUBMIT_LOGIN_SUCCESS = `${USER_ACTION}/SUBMIT_LOGIN_SUCCESS`;
export const SUBMIT_LOGIN_FAIL = `${USER_ACTION}/SUBMIT_LOGIN_FAIL`;
export const SET_USER_ID = `${USER_ACTION}/SET_USER_ID`;
export const SET_PASSWORD = `${USER_ACTION}/SET_PASSWORD`;
export const SET_STORE = `${USER_ACTION}/SET_STORE`;

const MESSAGE_ACTION = 'ruah/message';
export const GET_CONVERSATIONS = `${MESSAGE_ACTION}/GET_CONVERSATIONS`;
export const SET_CONVERSATIONS = `${MESSAGE_ACTION}/SET_CONVERSATIONS`;
export const SET_CONVERSATION = `${MESSAGE_ACTION}/SET_CONVERSATION`;
export const GET_CONVERSATIONS_LOCAL_SUCCESS = `${MESSAGE_ACTION}/GET_CONVERSATIONS_LOCAL_SUCCESS`;
export const GET_CONVERSATIONS_API_SUCCESS = `${MESSAGE_ACTION}/GET_CONVERSATIONS_API_SUCCESS`;
export const SET_MESSAGE_CONTENT = `${MESSAGE_ACTION}/SET_MESSAGE_CONTENT`;
export const SEND_MESSAGE = `${MESSAGE_ACTION}/SEND_MESSAGE`;

const PRODUCT_ACTION = 'ruah/product';
export const GET_COLLECTIONS = `${PRODUCT_ACTION}/GET_COLLECTIONS`;
export const SET_COLLECTIONS = `${PRODUCT_ACTION}/SET_COLLECTIONS`;
