const APP_ACTION = 'ruah/app';
export const LOAD_APP_ASSETS = `${APP_ACTION}/LOAD_APP_ASSETS`;
export const LOAD_APP_ASSETS_SUCCESS = `${APP_ACTION}/LOAD_APP_ASSETS_SUCCESS`;
export const LOAD_SQL_STORE = `${APP_ACTION}/LOAD_SQL_STORE`;
export const SET_SQL_STORE = `${APP_ACTION}/SET_SQL_STORE`;
export const SET_API_AUTH_TOKEN = `${APP_ACTION}/SET_API_AUTH_TOKEN`;

const USER_ACTION = 'ruah/user';
export const APP_SUBMIT_LOGIN = `${USER_ACTION}/APP_SUBMIT_LOGIN`;
export const USER_SUBMIT_LOGIN = `${USER_ACTION}/USER_SUBMIT_LOGIN`;
export const SUBMIT_LOGIN_SUCCESS = `${USER_ACTION}/SUBMIT_LOGIN_SUCCESS`;
export const SUBMIT_LOGIN_FAIL = `${USER_ACTION}/SUBMIT_LOGIN_FAIL`;
export const SET_USER_ID = `${USER_ACTION}/SET_USER_ID`;
export const SET_PASSWORD = `${USER_ACTION}/SET_PASSWORD`;

const MESSAGE_ACTION = 'ruah/message';
export const GET_CONVERSATIONS = `${MESSAGE_ACTION}/GET_CONVERSATIONS`;
export const SET_CONVERSATIONS = `${MESSAGE_ACTION}/SET_CONVERSATIONS`;
export const GET_CONVERSATIONS_LOCAL_SUCCESS = `${MESSAGE_ACTION}/GET_CONVERSATIONS_LOCAL_SUCCESS`;
export const GET_CONVERSATIONS_API_SUCCESS = `${MESSAGE_ACTION}/GET_CONVERSATIONS_API_SUCCESS`;
